version: '3'

services:
  stealthwebpage:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      ["./stealthwebpage:/opt/stealthwebpage"]
    environment:
      PORT: 80
      FLASK_DEBUG: True
      JWT_SECRET_KEY: "156334938555886735294293839154925725084" 
    ports:
      - "80:80"
